data:
  train_csv: "data/processed/train.csv"
  text_column: "text"
  target_column: "rating"

tokenizer:
  pretrained_model: "bert-base-uncased"
  max_length: 128

training:
  num_epochs: 1
  batch_size: 8
  learning_rate: 5e-5
  logging_steps: 10
  save_steps: 50
  save_strategy: "no"
  report_to: "none"

model:
  save_dir: "models/bert_model"
  log_dir: "C:/Users/nicho/BERT_Model/logs"
